/**
 * Les agences, loueurs et voyagistes de montagne relevés à côté des
 * plateformes, et les stations que chacun couvre.
 *
 * Demande du propriétaire du 26 septembre 2026 : Ski-Planet, Gens de
 * Confiance, Cimalpes, Alpissime, Ovo Network, Madame Vacances, Travelski,
 * Mountain Collection et Maeva. Les huit branchés ont chacun leur collecteur
 * dans ce dossier (`<source>.ts`, pur, et `<source>.server.ts`, le réseau).
 * Tous partent ensemble dans la part « agences » (`run.server.ts`), chacun
 * pour les seules stations qu'il couvre : une station qu'aucun ne couvre ne
 * leur coûte aucune requête, et l'écran n'en dit rien. Ce n'est pas une
 * panne, la source n'existe pas là.
 *
 * Gens de Confiance a été retiré le même jour, à la demande du propriétaire :
 * ses conditions d'utilisation interdisent la collecte automatisée.
 *
 * Les tables viennent des études du 26 septembre 2026, une par site : les
 * lieux que le site publie, rapprochés des stations du référentiel par le nom,
 * puis contrôlés à la distance de leurs logements.
 *
 * Module pur, sans réseau : l'écran Prix le lit aussi (`prix/releve.ts`).
 */

export const SOURCES_AGENCES = [
  "Alpissime",
  "Cimalpes",
  "Madame Vacances",
  "Maeva",
  "Mountain Collection",
  "Ovo Network",
  "Ski-Planet",
  "Travelski",
] as const;

export type SourceAgence = (typeof SOURCES_AGENCES)[number];

/**
 * Ovo Network : les destinations du site (paramètre `destination` de sa
 * recherche). Une destination rend aussi ses sous-destinations
 * (Saint-Gervais : Bionnassay et Saint-Nicolas de Véroce ; Combloux :
 * Domancy ; Morzine : Essert-Romand et La Côte d'Arbroz ; Chamonix : Les
 * Houches). Villards-sur-Thônes (15), que le site vend sous « Villards-sur-
 * Thônes - La Clusaz », est à 3 à 5 km de La Clusaz.
 */
const OVO: Readonly<Record<string, readonly string[]>> = {
  "la-clusaz": ["1", "15"],
  "le-grand-bornand": ["2"],
  manigod: ["5"],
  "saint-jean-de-sixt": ["6"],
  chamonix: ["61"],
  "les-houches": ["63"],
  combloux: ["114"],
  cordon: ["53"],
  "la-giettaz": ["40"],
  "les-contamines-montjoie": ["80"],
  megeve: ["86"],
  "saint-gervais-mont-blanc": ["101"],
  "saint-nicolas-de-veroce": ["253"],
  "les-carroz": ["79"],
  morillon: ["89"],
  samoens: ["99"],
  "sixt-fer-a-cheval": ["168"],
  "pralognan-la-vanoise": ["172"],
  "saint-martin-de-belleville": ["32"],
  chatel: ["66"],
  "la-chapelle-dabondance": ["72"],
  "les-gets": ["27"],
  montriond: ["213"],
  morzine: ["38"],
  "saint-jean-daulps": ["102"],
  "crest-voland-cohennoz": ["245"],
  "flumet-st-nicolas-la-chapelle": ["162"],
  "notre-dame-de-bellecombe": ["165"],
  "praz-sur-arly": ["166"],
  doucy: ["152"],
  valmorel: ["52"],
  "la-toussuire": ["176"],
  "le-corbier": ["177"],
  "les-arcs-bourg-st-maurice": ["78"],
  valmeinier: ["192"],
  "sainte-foy-tarentaise": ["173"],
  "les-2-alpes": ["146"],
  "la-grave-la-meije": ["147"],
  auron: ["271"],
  "font-romeu-pyrenees-2000": ["252"],
  gerardmer: ["266"],
};

/**
 * Alpissime : la station du site (`lieugeo` de sa recherche). Les stations
 * Skitrack plus fines (Arc 1800, Belle Plagne, Tignes Val Claret…) cherchent
 * dans leur station et ne gardent que leurs villages (`alpissime.ts`,
 * `VILLAGES`). Val Cenis n'avait aucune annonce avec prix, La Plagne et
 * Peisey-Vallandry rien de libre aux semaines essayées : elles restent, le
 * site peut en publier.
 */
const ALPISSIME: Readonly<Record<string, readonly string[]>> = {
  valloire: ["83"],
  "les-arcs-bourg-st-maurice": ["66"],
  tignes: ["79"],
  "la-plagne": ["62"],
  "la-clusaz": ["88"],
  "val-cenis": ["80"],
  "notre-dame-de-bellecombe": ["72"],
  "val-dallos-la-foux-le-seignus": ["22"],
  "flumet-st-nicolas-la-chapelle": ["103"],
  "crest-voland-cohennoz": ["85"],
  "saint-jean-de-sixt": ["137"],
  "peisey-vallandry": ["73"],
  "arc-1600": ["66"],
  "arc-1800": ["66"],
  "arc-1950": ["66"],
  "arc-2000": ["66"],
  "aime-2000": ["62"],
  "belle-plagne": ["62"],
  "champagny-en-vanoise": ["62"],
  "les-coches": ["62"],
  "montchavin-les-coches": ["62"],
  "plagne-bellecote": ["62"],
  "plagne-centre": ["62"],
  "plagne-villages": ["62"],
  "tignes-les-brevieres": ["79"],
  "tignes-val-claret": ["79"],
  "tignes-le-lac": ["79"],
  "tignes-les-boisses": ["79"],
  lanslebourg: ["80"],
  lanslevillard: ["80"],
  "la-foux-d-allos": ["22"],
  "le-seignus": ["22"],
};

/**
 * Mountain Collection : la zone du site (`id` de sa recherche). La zone de La
 * Plagne rend aussi les neuf stations de La Plagne, qui ont chacune leur
 * station Skitrack ; celle des Arcs n'a de logements qu'à Arc 1800 et Arc
 * 2000 ; « Montchavin » est côté Skitrack « Montchavin - Les Coches », Les
 * Coches ayant sa propre zone.
 */
const MOUNTAIN_COLLECTION: Readonly<Record<string, readonly string[]>> = {
  flaine: ["zte_1576"],
  "la-plagne": ["zte_1551"],
  "belle-plagne": ["zte_1556"],
  "la-plagne-montalbert": ["zte_1562"],
  "montchavin-les-coches": ["zte_1647"],
  "les-coches": ["zte_1648"],
  "plagne-1800": ["zte_1552"],
  "aime-2000": ["zte_1557"],
  "plagne-bellecote": ["zte_1554"],
  "plagne-centre": ["zte_1555"],
  "plagne-soleil": ["zte_1558"],
  "plagne-villages": ["zte_1553"],
  "la-rosiere-1850": ["zte_1546"],
  "la-toussuire": ["zte_1583"],
  "le-corbier": ["zte_1582"],
  "les-2-alpes": ["zte_1598"],
  "les-arcs-bourg-st-maurice": ["zte_1548"],
  "arc-1800": ["zte_1549"],
  "arc-2000": ["zte_1550"],
  "les-menuires": ["zte_1569"],
  reberty: ["zte_1570"],
  meribel: ["zte_1563"],
  "meribel-mottaret": ["zte_1564"],
  "pralognan-la-vanoise": ["zte_1675"],
  "saint-martin-de-belleville": ["zte_1568"],
  "serre-chevalier": ["zte_1584"],
  "serre-chevalier-briancon": ["zte_1585"],
  "serre-chevalier-chantemerle": ["zte_1586"],
  "serre-chevalier-le-monetier": ["zte_1588"],
  tignes: ["zte_1545"],
  "tignes-le-lac": ["zte_1630"],
  "tignes-val-claret": ["zte_1606"],
  "tignes-les-boisses": ["zte_1613"],
  "val-disere": ["zte_1544"],
  "la-daille": ["zte_1616"],
  "val-thorens": ["zte_1575"],
};

/**
 * Cimalpes : la station du site (`station_id`), et ses secteurs après un
 * deux-points (`secteurs[]`). Une station Skitrack qui a son secteur propre
 * ne prend que ce secteur ; la station du site entière ne va qu'à la station
 * Skitrack qui porte son nom. Non couverts : Mottaret, Arc 2000, Reberty,
 * Orelle, Brides, Le Tour, Vallorcine, Les Boisses, Les Brévières, Les
 * Contamines, Notre-Dame-de-Bellecombe, Praz-sur-Arly (secteurs absents ou
 * vides), et les villages de Serre Chevalier, que le site ne distingue pas.
 */
const CIMALPES: Readonly<Record<string, readonly string[]>> = {
  "alpe-d-huez": ["22"],
  "arc-1600": ["23:119"],
  "arc-1800": ["23:118"],
  "arc-1950": ["23:59"],
  argentiere: ["21:109"],
  chamonix: ["21"],
  combloux: ["5:29"],
  courchevel: ["1"],
  "courchevel-le-praz": ["1:7"],
  "courchevel-moriond-1650": ["1:5"],
  "courchevel-village-1550": ["1:6"],
  "crest-voland-cohennoz": ["57"],
  "la-daille": ["4:19"],
  "la-rosiere-1850": ["51"],
  "la-tania": ["1:32"],
  "le-bettex": ["46:113"],
  "le-fornet": ["4:23"],
  "les-2-alpes": ["49"],
  "les-arcs-bourg-st-maurice": ["23"],
  "les-houches": ["21:110"],
  "les-menuires": ["31"],
  "les-saisies": ["54"],
  megeve: ["5"],
  meribel: ["2"],
  "meribel-village": ["2:2"],
  morzine: ["27"],
  "saint-gervais-mont-blanc": ["46"],
  "saint-martin-de-belleville": ["17"],
  "saint-nicolas-de-veroce": ["46:112"],
  "serre-chevalier": ["47"],
  tignes: ["19"],
  "tignes-le-lac": ["19:39"],
  "tignes-val-claret": ["19:99"],
  "val-disere": ["4"],
  "val-thorens": ["25"],
};

/**
 * Madame Vacances : la station du site (`station` de sa recherche). Une
 * station Skitrack y figure quand elle porte le nom de la station du site,
 * qu'elle est la plus proche d'un de ses établissements, ou à 1 km au plus de
 * l'un d'eux. Les Bottières, Saint-Colomban et Valmeinier n'avaient aucune
 * disponibilité le jour de l'étude ; elles restent.
 */
const MADAME_VACANCES: Readonly<Record<string, readonly string[]>> = {
  abries: ["411"],
  "alpe-d-huez": ["127"],
  "auris-en-oisans": ["362"],
  courchevel: ["132"],
  "courchevel-village-1550": ["132"],
  flaine: ["134"],
  "savoie-grand-revard": ["140"],
  "la-mongie": ["394"],
  "la-mongie-bareges": ["394"],
  "la-plagne": ["142"],
  "plagne-soleil": ["142"],
  "plagne-villages": ["142"],
  "plagne-1800": ["142"],
  "plagne-centre": ["142"],
  "plagne-bellecote": ["142"],
  "la-rosiere-1850": ["313"],
  "la-tania": ["144"],
  "les-arcs-bourg-st-maurice": ["146"],
  "arc-2000": ["146"],
  "arc-1950": ["146"],
  "peisey-vallandry": ["404"],
  "les-bottieres": ["413"],
  "les-2-alpes": ["148"],
  "les-orres": ["117"],
  "les-orres-1800": ["117"],
  meribel: ["157"],
  "meribel-village": ["157"],
  "meribel-mottaret": ["256"],
  morillon: ["360"],
  "oz-en-oisans": ["161"],
  peyragudes: ["188"],
  "pralognan-la-vanoise": ["165"],
  "saint-colomban-villards": ["410"],
  "saint-sorlin-darves": ["169"],
  "besse-super-besse": ["317"],
  "val-disere": ["266"],
  "la-daille": ["266"],
  "le-fornet": ["266"],
  "val-thorens": ["176"],
  valfrejus: ["178"],
  valloire: ["180"],
  valmeinier: ["182"],
  valmorel: ["358"],
  doucy: ["358"],
  vaujany: ["242"],
};

/**
 * Maeva : les destinations du site (`station_cle` de sa recherche), relevées
 * par ses pages de département. Une destination présente n'a pas forcément
 * de logement libre à des dates données : 28 seulement en avaient aux dates
 * de l'étude.
 */
const MAEVA: Readonly<Record<string, readonly string[]>> = {
  abondance: ["6451"],
  "la-chapelle-dabondance": ["37"],
  argentiere: ["16"],
  avoriaz: ["19"],
  bernex: ["322"],
  chamonix: ["25"],
  chatel: ["28"],
  combloux: ["29"],
  cordon: ["2574"],
  flaine: ["32"],
  "la-clusaz": ["38"],
  "le-grand-bornand": ["48"],
  "les-carroz": ["53"],
  "les-contamines-montjoie": ["54"],
  "les-gets": ["55"],
  "les-houches": ["56"],
  manigod: ["212"],
  megeve: ["64"],
  montriond: ["353"],
  morillon: ["155"],
  morzine: ["68"],
  "praz-sur-arly": ["81"],
  "saint-gervais-mont-blanc": ["86", "1753"],
  "saint-jean-daulps": ["88"],
  samoens: ["93"],
  "sixt-fer-a-cheval": ["6520"],
  vallorcine: ["1175"],
  "saint-jean-de-sixt": ["520"],
  "praz-de-lys-sommand": ["569", "6492"],
  "les-haberes": ["349"],
  passy: ["1820"],
  "albiez-montrond": ["304"],
  "aime-2000": ["74"],
  "arc-1600": ["12"],
  "arc-1800": ["13"],
  "arc-1950": ["14"],
  "arc-2000": ["15"],
  "areches-beaufort": ["321"],
  aussois: ["223"],
  "belle-plagne": ["21"],
  bessans: ["333"],
  "bonneval-sur-arc": ["22"],
  "brides-les-bains": ["23"],
  "champagny-en-vanoise": ["26"],
  courchevel: ["30", "201311"],
  "courchevel-le-praz": ["1224"],
  "courchevel-moriond-1650": ["566"],
  "courchevel-village-1550": ["567"],
  "crest-voland-cohennoz": ["334", "4942"],
  doucy: ["31"],
  "flumet-st-nicolas-la-chapelle": ["588", "4931"],
  "la-giettaz": ["1812"],
  "la-norma": ["42"],
  "la-plagne-montalbert": ["77"],
  "la-rosiere-1850": ["43", "4897"],
  "la-tania": ["44"],
  "la-toussuire": ["45", "4874"],
  lanslebourg: ["4863"],
  lanslevillard: ["220451"],
  "le-corbier": ["47"],
  "les-arcs-bourg-st-maurice": ["611"],
  "les-bottieres": ["565"],
  "les-coches": ["66"],
  "les-karellis": ["57"],
  "les-menuires": ["58"],
  "les-saisies": ["61", "4840"],
  meribel: ["65"],
  "meribel-mottaret": ["318"],
  "meribel-village": ["319"],
  "montchavin-les-coches": ["373"],
  "notre-dame-de-bellecombe": ["69"],
  orelle: ["610"],
  "peisey-vallandry": ["72", "332"],
  "plagne-1800": ["377"],
  "plagne-bellecote": ["75"],
  "plagne-centre": ["76"],
  "plagne-soleil": ["78"],
  "plagne-villages": ["78"],
  "pralognan-la-vanoise": ["80"],
  "saint-colomban-villards": ["211"],
  "saint-francois-longchamp": ["85"],
  "saint-martin-de-belleville": ["90"],
  "saint-sorlin-darves": ["91"],
  "st-jean-darves": ["87", "220811"],
  "sainte-foy-tarentaise": ["92"],
  termignon: ["98"],
  "tignes-le-lac": ["574"],
  "tignes-les-boisses": ["372"],
  "tignes-les-brevieres": ["582"],
  "tignes-val-claret": ["573"],
  "val-cenis": ["101"],
  "val-disere": ["103"],
  "val-thorens": ["105"],
  valfrejus: ["104"],
  valloire: ["107"],
  valmeinier: ["108"],
  valmorel: ["109"],
  villaroger: ["5711"],
  "les-aillons-margeriaz": ["3113"],
  "savoie-grand-revard": ["568", "4856"],
  "alpe-d-huez": ["11"],
  "auris-en-oisans": ["17"],
  autrans: ["317", "150714"],
  chamrousse: ["27"],
  "gresse-en-vercors": ["35"],
  "lans-en-vercors": ["29994"],
  "les-2-alpes": ["50", "112"],
  "les-7-laux": ["329", "1133"],
  prapoutel: ["329"],
  "le-pleynet": ["1133"],
  "oz-en-oisans": ["71"],
  vaujany: ["111"],
  "villard-de-lans": ["113"],
  "villard-reculas": ["123534"],
  "correncon-en-vercors": ["346"],
  ancelle: ["1190"],
  arvieux: ["364"],
  ceillac: ["323"],
  "la-grave-la-meije": ["39"],
  "la-joue-du-loup": ["40"],
  "superdevoluy-la-joue-du-loup": ["97", "40"],
  "le-devoluy": ["260193", "3377"],
  "les-orres": ["59"],
  montgenevre: ["67"],
  nevache: ["3422"],
  orcieres: ["70", "1146"],
  "pelvoux-vallouise": ["390", "339"],
  "puy-saint-vincent": ["82"],
  risoul: ["84"],
  reallon: ["330"],
  chaillol: ["345"],
  "saint-leger-les-melezes": ["327"],
  "serre-chevalier-briancon": ["94"],
  "serre-chevalier-chantemerle": ["95"],
  "serre-chevalier-le-monetier": ["359"],
  "serre-chevalier": ["96"],
  vars: ["110"],
  abries: ["2928"],
  praloup: ["79"],
  "pra-loup-1500": ["79"],
  "la-foux-d-allos": ["102"],
  "val-dallos-la-foux-le-seignus": ["102"],
  chabanon: ["2128"],
  "sauze-supersauze": ["90504"],
  auron: ["18"],
  "isola-2000": ["36"],
  valberg: ["106"],
  "beuil-les-launes": ["282303"],
  bareges: ["20"],
  cauterets: ["24"],
  "la-mongie": ["41"],
  "la-mongie-bareges": ["41", "20"],
  peyragudes: ["73"],
  "piau-engaly": ["328"],
  "saint-lary-soulan": ["89"],
  "saint-lary-pla-d-adet": ["706"],
  "val-louron": ["358"],
  "gavarnie-gedre": ["6593", "6594"],
  "font-romeu-pyrenees-2000": ["33", "83"],
  "bolquere-pyrenees-2000": ["83", "6437"],
  "les-angles": ["52"],
  formigueres: ["7766"],
  puyvalador: ["6617"],
  "ax-3-domaines": ["6574", "302"],
  "luchon-superbagneres": ["62"],
  gourette: ["324"],
  gerardmer: ["34"],
  ventron: ["319863"],
  "xonrupt-le-poli": ["469", "319853"],
  "la-bresse-hohneck": ["594"],
  "le-lac-blanc": ["562"],
  "les-rousses": ["60", "775", "360"],
  "monts-jura": ["342"],
  "besse-super-besse": ["224", "1279"],
  "chastreix-sancy": ["2129"],
  "la-bourboule": ["1156"],
  "le-mont-dore": ["49"],
  "le-lioran": ["260113"],
  "le-bleymard": ["1915"],
  "les-estables": ["557"],
  laguiole: ["2452"],
};

/**
 * Travelski : le lieu du catalogue (`/se/search/geodata/1`), une station
 * (`station`) ou un ensemble (`parentStation` : La Plagne, Tignes…), et ses
 * identifiants : plusieurs passent dans une seule recherche (Les Arcs avec
 * Bourg-Saint-Maurice). Seul `courchevel` est plus large que la station
 * Skitrack : l'ensemble du site compte La Tania.
 */
const TRAVELSKI: Readonly<Record<string, readonly string[]>> = {
  "aime-2000": ["station:87"],
  "albiez-montrond": ["station:148"],
  "alpe-d-huez": ["station:7"],
  "arc-1600": ["station:96"],
  "arc-1800": ["station:27"],
  "arc-1950": ["station:336"],
  "arc-2000": ["station:97"],
  "auris-en-oisans": ["station:89"],
  auron: ["station:63"],
  aussois: ["station:149"],
  avoriaz: ["station:36"],
  "ax-3-domaines": ["station:90"],
  "belle-plagne": ["station:116"],
  "besse-super-besse": ["station:124"],
  "brides-les-bains": ["station:25"],
  chamonix: ["station:140"],
  "champagny-en-vanoise": ["station:121"],
  chamrousse: ["station:57"],
  chatel: ["station:82"],
  combloux: ["station:141"],
  courchevel: ["parentStation:5"],
  "courchevel-moriond-1650": ["station:150"],
  "courchevel-village-1550": ["station:46"],
  doucy: ["station:95"],
  flaine: ["parentStation:110034"],
  "font-romeu-pyrenees-2000": ["station:84"],
  "isola-2000": ["station:9"],
  "la-clusaz": ["station:142"],
  "la-daille": ["station:14110"],
  "la-foux-d-allos": ["station:70"],
  "la-joue-du-loup": ["station:91"],
  "la-norma": ["station:83"],
  "la-plagne": ["parentStation:4"],
  "la-plagne-montalbert": ["station:94"],
  "la-rosiere-1850": ["station:151"],
  "la-tania": ["station:26"],
  "la-toussuire": ["station:49"],
  lanslebourg: ["station:14101"],
  lanslevillard: ["station:14102"],
  "le-corbier": ["station:51"],
  "le-grand-bornand": ["station:143"],
  "les-2-alpes": ["parentStation:110032"],
  "les-angles": ["station:157"],
  "les-arcs-bourg-st-maurice": ["station:96,27,336,97,350"],
  "les-carroz": ["station:117"],
  "les-coches": ["station:789"],
  "les-gets": ["station:144"],
  "les-houches": ["station:92"],
  "les-menuires": ["station:14089,14087,14090,14086,14120,14091,14088"],
  "les-orres": ["station:66"],
  "les-saisies": ["station:153"],
  megeve: ["station:125"],
  meribel: ["parentStation:110031"],
  "meribel-mottaret": ["station:14096"],
  "meribel-village": ["station:14093"],
  "montchavin-les-coches": ["station:54"],
  montgenevre: ["station:134"],
  morillon: ["parentStation:10029"],
  morzine: ["station:145"],
  orcieres: ["station:67"],
  orelle: ["station:375"],
  "oz-en-oisans": ["station:58"],
  "peisey-vallandry": ["parentStation:110035"],
  peyragudes: ["station:85"],
  "plagne-1800": ["station:93"],
  "plagne-bellecote": ["station:41"],
  "plagne-centre": ["station:42"],
  "plagne-soleil": ["station:40"],
  "plagne-villages": ["station:329"],
  "pralognan-la-vanoise": ["station:52"],
  praloup: ["station:69"],
  "puy-saint-vincent": ["station:65"],
  reberty: ["station:14090,14091"],
  risoul: ["station:8"],
  "saint-francois-longchamp": ["station:31"],
  "saint-gervais-mont-blanc": ["station:129"],
  "saint-jean-de-sixt": ["station:9537"],
  "saint-lary-soulan": ["station:118"],
  "saint-martin-de-belleville": ["station:154"],
  "saint-sorlin-darves": ["station:53"],
  "sainte-foy-tarentaise": ["station:327"],
  samoens: ["station:80"],
  "serre-chevalier": ["parentStation:10022"],
  "serre-chevalier-briancon": ["station:133"],
  "serre-chevalier-chantemerle": ["station:20"],
  "serre-chevalier-le-monetier": ["station:2442"],
  "st-jean-darves": ["station:50"],
  "superdevoluy-la-joue-du-loup": ["station:88,91"],
  termignon: ["station:122"],
  tignes: ["parentStation:110033"],
  "tignes-le-lac": ["station:14108"],
  "tignes-les-brevieres": ["station:14061"],
  "tignes-val-claret": ["station:1825"],
  "val-cenis": ["parentStation:10023"],
  "val-disere": ["parentStation:110036"],
  "val-thorens": ["station:23"],
  valfrejus: ["station:47"],
  valloire: ["station:48"],
  valmeinier: ["station:30"],
  valmorel: ["station:22"],
  vars: ["station:10"],
  vaujany: ["station:56"],
};

/**
 * Ski-Planet : la station de chaque résidence, telle que l'autocomplétion du
 * site l'écrit (« - Avoriaz »), en slug. C'est la clé de la table des
 * résidences (`skiPlanet.residences.json`). Le site ne sépare pas les
 * sous-stations (Arc 1800, Tignes Le Lac) de leur station : elles n'ont pas
 * d'entrée, plutôt que les résidences de toute la station. Orelle, seule, a
 * les siennes. Rattachements de jugement : La Féclaz (Savoie Grand Revard),
 * La Bresse (La Bresse Hohneck), Manigod l'Etale, Barèges La Mongie.
 */
const SKI_PLANET: Readonly<Record<string, readonly string[]>> = {
  "albiez-montrond": ["albiez-montrond"],
  "alpe-d-huez": ["alpe-d-huez"],
  "areches-beaufort": ["areches-beaufort"],
  "auris-en-oisans": ["auris-en-oisans"],
  auron: ["auron"],
  aussois: ["aussois"],
  autrans: ["autrans-meaudre-en-vercors"],
  avoriaz: ["avoriaz"],
  "ax-3-domaines": ["ax-les-thermes"],
  "bellevaux-hirmentaz": ["hirmentaz"],
  bessans: ["bessans"],
  "besse-super-besse": ["super-besse"],
  "bolquere-pyrenees-2000": ["pyrenees-2000"],
  "brides-les-bains": ["brides-les-bains"],
  cauterets: ["cauterets"],
  chabanon: ["chabanon-selonnet"],
  chamonix: ["chamonix"],
  "champagny-en-vanoise": ["champagny-en-vanoise"],
  chamrousse: ["chamrousse"],
  chatel: ["chatel"],
  combloux: ["combloux"],
  courchevel: ["courchevel"],
  flaine: ["flaine"],
  "flumet-st-nicolas-la-chapelle": ["flumet"],
  "font-romeu-pyrenees-2000": ["font-romeu"],
  gourette: ["gourette"],
  "gresse-en-vercors": ["gresse-en-vercors"],
  guzet: ["guzet"],
  "isola-2000": ["isola-2000"],
  "la-bresse-hohneck": ["la-bresse"],
  "la-chapelle-dabondance": ["la-chapelle-d-abondance"],
  "la-clusaz": ["la-clusaz"],
  "la-joue-du-loup": ["la-joue-du-loup"],
  "la-mongie-bareges": ["bareges-la-mongie"],
  "la-norma": ["la-norma"],
  "la-plagne": ["la-plagne"],
  "la-plagne-montalbert": ["montalbert"],
  "la-rosiere-1850": ["la-rosiere"],
  "la-tania": ["la-tania"],
  "la-toussuire": ["la-toussuire"],
  "le-collet-dallevard": ["le-collet-d-allevard"],
  "le-corbier": ["le-corbier"],
  "le-grand-bornand": ["le-grand-bornand"],
  "les-2-alpes": ["les-2-alpes"],
  "les-7-laux": ["les-7-laux"],
  "les-angles": ["les-angles"],
  "les-arcs-bourg-st-maurice": ["les-arcs"],
  "les-bottieres": ["les-bottieres"],
  "les-carroz": ["les-carroz"],
  "les-contamines-montjoie": ["les-contamines-montjoie"],
  "les-gets": ["les-gets"],
  "les-houches": ["les-houches"],
  "les-menuires": ["les-menuires"],
  "les-orres": ["les-orres"],
  "les-saisies": ["les-saisies"],
  "luchon-superbagneres": ["luchon-superbagneres"],
  "luz-ardiden": ["luz-ardiden"],
  manigod: ["manigod-l-etale"],
  megeve: ["megeve"],
  meribel: ["meribel"],
  "meribel-mottaret": ["meribel-mottaret"],
  "montchavin-les-coches": ["montchavin-la-plagne"],
  montgenevre: ["montgenevre"],
  morillon: ["morillon"],
  morzine: ["morzine"],
  "notre-dame-de-bellecombe": ["notre-dame-de-bellecombe"],
  orcieres: ["orcieres-merlette-1850"],
  orelle: ["orelle"],
  "oz-en-oisans": ["oz-3300"],
  "peisey-vallandry": ["peisey-vallandry"],
  "pelvoux-vallouise": ["pelvoux"],
  peyragudes: ["peyragudes"],
  "piau-engaly": ["piau-engaly"],
  "pralognan-la-vanoise": ["pralognan-la-vanoise"],
  praloup: ["pra-loup"],
  "praz-sur-arly": ["praz-sur-arly"],
  "puy-saint-vincent": ["puy-saint-vincent"],
  risoul: ["risoul"],
  "saint-colomban-villards": ["saint-colomban-des-villards"],
  "saint-francois-longchamp": ["saint-francois-longchamp"],
  "saint-gervais-mont-blanc": ["saint-gervais"],
  "saint-lary-soulan": ["saint-lary-soulan"],
  "saint-martin-de-belleville": ["saint-martin-de-belleville"],
  "saint-sorlin-darves": ["saint-sorlin-d-arves"],
  samoens: ["samoens"],
  "sauze-supersauze": ["sauze-super-sauze"],
  "savoie-grand-revard": ["la-feclaz"],
  "serre-chevalier": ["serre-chevalier"],
  "st-jean-darves": ["saint-jean-d-arves"],
  "superdevoluy-la-joue-du-loup": ["superdevoluy"],
  "thollon-les-memises": ["thollon-les-memises"],
  tignes: ["tignes"],
  "val-cenis": ["val-cenis"],
  "val-dallos-la-foux-le-seignus": ["val-d-allos"],
  "val-disere": ["val-d-isere"],
  "val-thorens": ["val-thorens"],
  valberg: ["valberg-beuil"],
  valfrejus: ["valfrejus"],
  valloire: ["valloire"],
  valmeinier: ["valmeinier"],
  valmorel: ["valmorel"],
  vars: ["vars"],
  vaujany: ["vaujany"],
  "villard-de-lans": ["villard-de-lans"],
};

const TABLES: Readonly<Record<SourceAgence, Readonly<Record<string, readonly string[]>>>> = {
  Alpissime: ALPISSIME,
  Cimalpes: CIMALPES,
  "Madame Vacances": MADAME_VACANCES,
  Maeva: MAEVA,
  "Mountain Collection": MOUNTAIN_COLLECTION,
  "Ovo Network": OVO,
  "Ski-Planet": SKI_PLANET,
  Travelski: TRAVELSKI,
};

/** Les stations Skitrack qu'une source couvre : les clés de sa table. */
export function stationsDe(source: SourceAgence): string[] {
  return Object.keys(TABLES[source]);
}

/** Les lieux du site pour une station Skitrack, dans l'ordre de la table ; aucun si la source ne la couvre pas. */
export function lieuxDe(source: SourceAgence, stationId: string): readonly string[] {
  return TABLES[source][stationId] ?? [];
}

/** Les sources qui couvrent la station, dans l'ordre de `SOURCES_AGENCES`. */
export function agencesDe(stationId: string): SourceAgence[] {
  return SOURCES_AGENCES.filter((s) => lieuxDe(s, stationId).length > 0);
}
