/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Sonde du handshake Electron. Volontairement hors authentification et sans
         *     accès base : elle doit répondre même si SQLite est verrouillé.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description État fonctionnel : y a-t-il un référentiel exploitable ?
         */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Domains */
        post: operations["search_domains_api_domains_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Facets
         * @description Valeurs disponibles pour alimenter les filtres — évite de proposer un
         *     massif ou un pays qui ne renverrait aucun résultat.
         */
        get: operations["facets_api_domains_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Points
         * @description Points pour la carte, en GeoJSON minimal.
         *
         *     Endpoint séparé de la recherche : la carte a besoin de *tous* les domaines
         *     pour le clustering, la liste n'a besoin que de la page courante. Les
         *     mélanger obligerait à renvoyer 300 fiches complètes à chaque frappe.
         */
        get: operations["map_points_api_domains_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/{domain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain */
        get: operations["get_domain_api_domains__domain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Origins */
        get: operations["list_origins_api_geo_origins_get"];
        put?: never;
        /** Create Origin */
        post: operations["create_origin_api_geo_origins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/origins/{origin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Origin */
        delete: operations["delete_origin_api_geo_origins__origin_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode Endpoint */
        get: operations["geocode_endpoint_api_geo_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/elevation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Elevation Endpoint */
        post: operations["elevation_endpoint_api_geo_elevation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/routes/precompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Precompute Routes
         * @description Pré-calcule les temps de trajet origine → domaines, en tâche de fond.
         *
         *     Deux garde-fous contre l'explosion de quota :
         *
         *     1. Pré-filtre à vol d'oiseau (`max_crow_km`) — gratuit, il élimine d'emblée
         *        les domaines hors de portée.
         *     2. Réutilisation : un couple (origine, domaine, profil) déjà calculé n'est
         *        pas recalculé.
         */
        post: operations["precompute_routes_api_geo_routes_precompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/routes/{domain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route To Domain
         * @description Trajet exact vers un domaine — c'est ici que l'évitement des péages est
         *     réellement appliqué (voir services/routing.py).
         */
        post: operations["route_to_domain_api_geo_routes__domain_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/isochrones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Isochrones */
        post: operations["isochrones_api_geo_isochrones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referential/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_referential_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referential/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Import */
        post: operations["start_import_api_referential_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referential/curated/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reapply Curated
         * @description Recharge le YAML curaté sans refaire l'import — pratique pendant la saisie.
         */
        post: operations["reapply_curated_api_referential_curated_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referential/glaciers/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Glacier Detection */
        post: operations["start_glacier_detection_api_referential_glaciers_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referential/dumps/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dump */
        delete: operations["delete_dump_api_referential_dumps__kind__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/settings/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push Secrets */
        post: operations["push_secrets_api_settings_secrets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deeplinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deeplinks
         * @description Construit les URLs de recherche pré-remplies. Aucune n'est appelée ici :
         *     l'app se contente de les fabriquer, l'utilisateur décide de les ouvrir.
         */
        post: operations["deeplinks_api_deeplinks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deeplinks/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deeplinks Reload */
        post: operations["deeplinks_reload_api_deeplinks_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Cache
         * @description Purge du cache HTTP. `namespace` parmi elevation / route / geocode /
         *     weather / offer — purger les altitudes n'a aucun intérêt et coûte des
         *     milliers d'appels, d'où la purge sélective.
         */
        delete: operations["clear_cache_api_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DeepLink */
        DeepLink: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
            /**
             * Verified
             * @default false
             */
            verified: string | boolean;
            /** Note */
            note?: string | null;
        };
        /** DeepLinkRequest */
        DeepLinkRequest: {
            /** Query */
            query: string;
            /** Check In */
            check_in?: string | null;
            /** Check Out */
            check_out?: string | null;
            /**
             * Adults
             * @default 2
             */
            adults: number;
            /**
             * Bedrooms
             * @default 1
             */
            bedrooms: number;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Domain Slug */
            domain_slug?: string | null;
        };
        /** DomainAccessOut */
        DomainAccessOut: {
            /** Profile */
            profile: string;
            /** Duration Min */
            duration_min?: number | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Crow Km */
            crow_km?: number | null;
            /** Provider */
            provider?: string | null;
            /** Computed At */
            computed_at?: string | null;
        };
        /** DomainDetailOut */
        DomainDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** Massif */
            massif?: string | null;
            /** Status */
            status: string;
            /** Altitude Min M */
            altitude_min_m?: number | null;
            /** Altitude Max M */
            altitude_max_m?: number | null;
            /** Altitude Village M */
            altitude_village_m?: number | null;
            /** Altitude Source */
            altitude_source: string;
            /** Slopes Km Total */
            slopes_km_total?: number | null;
            /** Slopes Km By Color */
            slopes_km_by_color?: {
                [key: string]: number;
            } | null;
            /** Slopes Count By Color */
            slopes_count_by_color?: {
                [key: string]: number;
            } | null;
            /** Lifts Count */
            lifts_count?: number | null;
            /** Glacier */
            glacier?: boolean | null;
            /** Snowmaking Pct */
            snowmaking_pct?: number | null;
            /** Linked Pass Name */
            linked_pass_name?: string | null;
            /** Official Website Url */
            official_website_url?: string | null;
            /** Official Booking Url */
            official_booking_url?: string | null;
            /** Centroid Lat */
            centroid_lat?: number | null;
            /** Centroid Lon */
            centroid_lon?: number | null;
            /**
             * Curated
             * @default false
             */
            curated: boolean;
            access?: components["schemas"]["DomainAccessOut"] | null;
            /** Score */
            score?: number | null;
            /** Score Breakdown */
            score_breakdown?: {
                [key: string]: number;
            } | null;
            /** Localities */
            localities?: string[] | null;
            /** Admin Code */
            admin_code?: string | null;
            /** Lifts Count By Type */
            lifts_count_by_type?: {
                [key: string]: number;
            } | null;
            /** Lifts Km Total */
            lifts_km_total?: number | null;
            /** North Facing Pct */
            north_facing_pct?: number | null;
            /** Season Open Typical */
            season_open_typical?: string | null;
            /** Season Close Typical */
            season_close_typical?: string | null;
            /** Wikidata Id */
            wikidata_id?: string | null;
            /** Osm Id */
            osm_id?: string | null;
            /** Source */
            source: string;
            /** Source Id */
            source_id: string;
            /** Bbox */
            bbox?: number[] | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes?: string | null;
            /** Lifts */
            lifts?: components["schemas"]["LiftOut"][];
            /**
             * Slopes Available
             * @default false
             */
            slopes_available: boolean;
        };
        /**
         * DomainSearchRequest
         * @description Filtres de l'écran 1.
         *
         *     Tout est optionnel : une requête vide renvoie tous les domaines en
         *     exploitation, ce qui rend l'écran utilisable avant même d'avoir saisi une
         *     adresse de départ.
         */
        DomainSearchRequest: {
            /**
             * Query
             * @description Recherche plein texte sur le nom
             */
            query?: string | null;
            /**
             * Countries
             * @description Codes ISO 3166-1 alpha-2
             */
            countries?: string[] | null;
            /** Massifs */
            massifs?: string[] | null;
            /** Status */
            status?: string[];
            /**
             * Altitude Min M
             * @description Bas des pistes ≥ cette valeur — critère neige décisif
             */
            altitude_min_m?: number | null;
            /**
             * Altitude Max M
             * @description Point culminant ≥
             */
            altitude_max_m?: number | null;
            /** Altitude Village Min M */
            altitude_village_min_m?: number | null;
            /** Slopes Km Min */
            slopes_km_min?: number | null;
            /** Lifts Count Min */
            lifts_count_min?: number | null;
            /** Glacier */
            glacier?: boolean | null;
            /** Snowmaking Pct Min */
            snowmaking_pct_min?: number | null;
            /**
             * Linked Only
             * @default false
             */
            linked_only: boolean;
            /**
             * Origin Id
             * @description Si fourni, joint les temps de trajet et permet de filtrer dessus
             */
            origin_id?: number | null;
            /** Max Car Time Min */
            max_car_time_min?: number | null;
            /** Max Car Distance Km */
            max_car_distance_km?: number | null;
            /**
             * Avoid Tolls
             * @default false
             */
            avoid_tolls: boolean;
            /**
             * Sort
             * @default relevance
             * @enum {string}
             */
            sort: "relevance" | "altitude_min_desc" | "altitude_max_desc" | "slopes_km_desc" | "travel_time_asc" | "name_asc";
            /**
             * Limit
             * @default 200
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** DomainSearchResponse */
        DomainSearchResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["DomainSummaryOut"][];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DomainSummaryOut
         * @description Charge utile d'une ligne de résultat. Volontairement sans `geometry` :
         *     300 emprises polygonales alourdiraient la réponse de plusieurs Mo alors que
         *     la carte se contente des centroïdes pour le clustering.
         */
        DomainSummaryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** Massif */
            massif?: string | null;
            /** Status */
            status: string;
            /** Altitude Min M */
            altitude_min_m?: number | null;
            /** Altitude Max M */
            altitude_max_m?: number | null;
            /** Altitude Village M */
            altitude_village_m?: number | null;
            /** Altitude Source */
            altitude_source: string;
            /** Slopes Km Total */
            slopes_km_total?: number | null;
            /** Slopes Km By Color */
            slopes_km_by_color?: {
                [key: string]: number;
            } | null;
            /** Slopes Count By Color */
            slopes_count_by_color?: {
                [key: string]: number;
            } | null;
            /** Lifts Count */
            lifts_count?: number | null;
            /** Glacier */
            glacier?: boolean | null;
            /** Snowmaking Pct */
            snowmaking_pct?: number | null;
            /** Linked Pass Name */
            linked_pass_name?: string | null;
            /** Official Website Url */
            official_website_url?: string | null;
            /** Official Booking Url */
            official_booking_url?: string | null;
            /** Centroid Lat */
            centroid_lat?: number | null;
            /** Centroid Lon */
            centroid_lon?: number | null;
            /**
             * Curated
             * @default false
             */
            curated: boolean;
            access?: components["schemas"]["DomainAccessOut"] | null;
            /** Score */
            score?: number | null;
            /** Score Breakdown */
            score_breakdown?: {
                [key: string]: number;
            } | null;
        };
        /** ElevationPoint */
        ElevationPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Elevation M */
            elevation_m: number | null;
            /** Provider */
            provider?: string | null;
        };
        /** ElevationRequest */
        ElevationRequest: {
            /**
             * Points
             * @description Liste de (lat, lon)
             */
            points: [
                number,
                number
            ][];
            /**
             * Prefer
             * @default auto
             * @enum {string}
             */
            prefer: "auto" | "ign" | "opentopodata";
        };
        /** ElevationResponse */
        ElevationResponse: {
            /** Points */
            points: components["schemas"]["ElevationPoint"][];
            /**
             * Cached
             * @default 0
             */
            cached: number;
            /**
             * Fetched
             * @default 0
             */
            fetched: number;
        };
        /** GeocodeResult */
        GeocodeResult: {
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Score */
            score?: number | null;
            /** City */
            city?: string | null;
            /** Postcode */
            postcode?: string | null;
            /** Provider */
            provider: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Countries */
            countries?: string[];
            /**
             * With Lifts
             * @default true
             */
            with_lifts: boolean;
            /**
             * With Runs
             * @default true
             */
            with_runs?: boolean;
            /**
             * Detect Glaciers
             * @default false
             */
            detect_glaciers: boolean;
            /**
             * Force Download
             * @default false
             */
            force_download: boolean;
            /** Ski Areas File */
            ski_areas_file?: string | null;
            /** Lifts File */
            lifts_file?: string | null;
        };
        /** IsochroneRequest */
        IsochroneRequest: {
            /** Origin Id */
            origin_id: number;
            /** Ranges Min */
            ranges_min?: number[];
            /**
             * Profile
             * @default car
             * @enum {string}
             */
            profile: "car" | "car_no_toll";
        };
        /** IsochroneResponse */
        IsochroneResponse: {
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
            /** Provider */
            provider: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /**
         * JobStatus
         * @description Suivi d'une tâche longue (import du référentiel, pré-calcul des trajets).
         */
        JobStatus: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "error" | "cancelled";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** LiftOut */
        LiftOut: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Lift Type */
            lift_type?: string | null;
            /** Length M */
            length_m?: number | null;
            /** Elevation Min M */
            elevation_min_m?: number | null;
            /** Elevation Max M */
            elevation_max_m?: number | null;
            /** Base Lat */
            base_lat?: number | null;
            /** Base Lon */
            base_lon?: number | null;
        };
        /** OriginIn */
        OriginIn: {
            /** Label */
            label: string;
            /** Address */
            address: string;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /**
             * Is Default
             * @default true
             */
            is_default: boolean;
        };
        /** OriginOut */
        OriginOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Geocoder */
            geocoder?: string | null;
            /** Is Default */
            is_default: boolean;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lodging" | "routing" | "elevation" | "weather" | "geocoding";
            /** Enabled */
            enabled: boolean;
            /** Configured */
            configured: boolean;
            /** Label */
            label: string;
            /** Reason */
            reason?: string | null;
            /** Docs Url */
            docs_url?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /** RoutePrecomputeRequest */
        RoutePrecomputeRequest: {
            /** Origin Id */
            origin_id: number;
            /**
             * Profile
             * @default car
             * @enum {string}
             */
            profile: "car" | "car_no_toll";
            /**
             * Max Crow Km
             * @description Pré-filtre à vol d'oiseau. Au-delà, aucun appel au routeur : le quota gratuit d'OpenRouteService ne survit pas à 300 itinéraires vers des domaines évidemment hors de portée.
             * @default 900
             */
            max_crow_km: number;
            /** Domain Ids */
            domain_ids?: number[] | null;
        };
        /**
         * SecretsPayload
         * @description Clés d'API poussées par Electron après déchiffrement DPAPI.
         *
         *     Elles restent en mémoire du sidecar. Rien n'est écrit en base ni en log.
         */
        SecretsPayload: {
            /** Values */
            values?: {
                [key: string]: string;
            };
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Values */
            values?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_domains_api_domains_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facets_api_domains_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    map_points_api_domains_map_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_api_domains__domain_id__get: {
        parameters: {
            query?: {
                origin_id?: number | null;
                avoid_tolls?: boolean;
            };
            header?: never;
            path: {
                domain_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_origins_api_geo_origins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginOut"][];
                };
            };
        };
    };
    create_origin_api_geo_origins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OriginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_origin_api_geo_origins__origin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                origin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_endpoint_api_geo_geocode_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elevation_endpoint_api_geo_elevation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElevationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precompute_routes_api_geo_routes_precompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutePrecomputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_to_domain_api_geo_routes__domain_id__post: {
        parameters: {
            query: {
                origin_id: number;
                avoid_tolls?: boolean;
            };
            header?: never;
            path: {
                domain_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    isochrones_api_geo_isochrones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IsochroneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsochroneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_referential_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    start_import_api_referential_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reapply_curated_api_referential_curated_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    start_glacier_detection_api_referential_glaciers_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dump_api_referential_dumps__kind__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_secrets_api_settings_secrets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    deeplinks_api_deeplinks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deeplinks_reload_api_deeplinks_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_api_cache_delete: {
        parameters: {
            query?: {
                namespace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
