/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AltitudesRouteImport } from './routes/altitudes'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as ForfaitsRouteImport } from './routes/forfaits'
import { Route as LogementsRouteImport } from './routes/logements'
import { Route as OpenskimapRouteImport } from './routes/openskimap'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as StationsIdRouteImport } from './routes/stations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AltitudesRoute = AltitudesRouteImport.update({
  id: '/altitudes',
  path: '/altitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForfaitsRoute = ForfaitsRouteImport.update({
  id: '/forfaits',
  path: '/forfaits',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsRoute = LogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenskimapRoute = OpenskimapRouteImport.update({
  id: '/openskimap',
  path: '/openskimap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIdRoute = StationsIdRouteImport.update({
  id: '/stations/$id',
  path: '/stations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/altitudes': typeof AltitudesRoute
  '/carte': typeof CarteRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/openskimap': typeof OpenskimapRoute
  '/reservation': typeof ReservationRoute
  '/traces': typeof TracesRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/altitudes': typeof AltitudesRoute
  '/carte': typeof CarteRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/openskimap': typeof OpenskimapRoute
  '/reservation': typeof ReservationRoute
  '/traces': typeof TracesRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/altitudes': typeof AltitudesRoute
  '/carte': typeof CarteRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/openskimap': typeof OpenskimapRoute
  '/reservation': typeof ReservationRoute
  '/traces': typeof TracesRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/altitudes'
    | '/carte'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/openskimap'
    | '/reservation'
    | '/traces'
    | '/stations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/altitudes'
    | '/carte'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/openskimap'
    | '/reservation'
    | '/traces'
    | '/stations/$id'
  id:
    | '__root__'
    | '/'
    | '/altitudes'
    | '/carte'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/openskimap'
    | '/reservation'
    | '/traces'
    | '/stations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AltitudesRoute: typeof AltitudesRoute
  CarteRoute: typeof CarteRoute
  ComparerRoute: typeof ComparerRoute
  ForfaitsRoute: typeof ForfaitsRoute
  LogementsRoute: typeof LogementsRoute
  OpenskimapRoute: typeof OpenskimapRoute
  ReservationRoute: typeof ReservationRoute
  TracesRoute: typeof TracesRoute
  StationsIdRoute: typeof StationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altitudes': {
      id: '/altitudes'
      path: '/altitudes'
      fullPath: '/altitudes'
      preLoaderRoute: typeof AltitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forfaits': {
      id: '/forfaits'
      path: '/forfaits'
      fullPath: '/forfaits'
      preLoaderRoute: typeof ForfaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements': {
      id: '/logements'
      path: '/logements'
      fullPath: '/logements'
      preLoaderRoute: typeof LogementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openskimap': {
      id: '/openskimap'
      path: '/openskimap'
      fullPath: '/openskimap'
      preLoaderRoute: typeof OpenskimapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$id': {
      id: '/stations/$id'
      path: '/stations/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AltitudesRoute: AltitudesRoute,
  CarteRoute: CarteRoute,
  ComparerRoute: ComparerRoute,
  ForfaitsRoute: ForfaitsRoute,
  LogementsRoute: LogementsRoute,
  OpenskimapRoute: OpenskimapRoute,
  ReservationRoute: ReservationRoute,
  TracesRoute: TracesRoute,
  StationsIdRoute: StationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
