/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as ForfaitsRouteImport } from './routes/forfaits'
import { Route as LogementsRouteImport } from './routes/logements'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as ReservationIdRouteImport } from './routes/reservation.$id'
import { Route as StationsIdRouteImport } from './routes/stations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForfaitsRoute = ForfaitsRouteImport.update({
  id: '/forfaits',
  path: '/forfaits',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsRoute = LogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIdRoute = StationsIdRouteImport.update({
  id: '/stations/$id',
  path: '/stations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/traces': typeof TracesRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/traces': typeof TracesRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparer': typeof ComparerRoute
  '/forfaits': typeof ForfaitsRoute
  '/logements': typeof LogementsRoute
  '/traces': typeof TracesRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/stations/$id': typeof StationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/traces'
    | '/reservation/$id'
    | '/stations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/traces'
    | '/reservation/$id'
    | '/stations/$id'
  id:
    | '__root__'
    | '/'
    | '/comparer'
    | '/forfaits'
    | '/logements'
    | '/traces'
    | '/reservation/$id'
    | '/stations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparerRoute: typeof ComparerRoute
  ForfaitsRoute: typeof ForfaitsRoute
  LogementsRoute: typeof LogementsRoute
  TracesRoute: typeof TracesRoute
  ReservationIdRoute: typeof ReservationIdRoute
  StationsIdRoute: typeof StationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forfaits': {
      id: '/forfaits'
      path: '/forfaits'
      fullPath: '/forfaits'
      preLoaderRoute: typeof ForfaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements': {
      id: '/logements'
      path: '/logements'
      fullPath: '/logements'
      preLoaderRoute: typeof LogementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$id': {
      id: '/stations/$id'
      path: '/stations/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparerRoute: ComparerRoute,
  ForfaitsRoute: ForfaitsRoute,
  LogementsRoute: LogementsRoute,
  TracesRoute: TracesRoute,
  ReservationIdRoute: ReservationIdRoute,
  StationsIdRoute: StationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
